### ISSUE TITLE
City population shown as 0%

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#81]
version 2,0
http://citygenerator.morgajel.net//citygenerator?seed=792569
http://citygenerator.morgajel.net/citygenerator?seed=792538

In each of these cities there is a part of the population listed as 0%.  Those should not show.

Example:
0 halflings (0%)

**Comment by morgajel** [comment]
yeah, this is totally a bug. if 0, it should remove it completely.

**Comment by morgajel** [comment]
Unfortunately I _just_ fixed this on the back end with commit c0a6067ae3e99d71ea522fa7ee30dec18dee2327 (refactored wall code to be more overridable) so that these conditions should not happen again.

However if you'd be willing to give ticket #90 a stab I'd appreciate it (and 116 if you're really feeling froggy).
