### ISSUE TITLE
Establishment verbiage and general inconsistancy.

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#83]
The establishment data needs to be proofread.

Example:
x woods  <-- should be a resource.  
x ponds <-- should be a resource.  
x beer-sellers <-- hypen?
x law enforcements <-- does not parse
xscabbardmakerss <-- lots of entries with double s
x shops <-- to generic.

**Comment by morgajel** [comment]
Since we calculate businesses according to the number of specialists we have,  we need to find better business locations for certain specialists. For example, Watercarriers "work" at a pond or stream currently. A) we need to find a better place for them to work and b) we need to figure out a way to ignore someone who doesn't have a place of business.

**Comment by braddoro** [comment]
I think giving each of them a narrative will solve the problem.  Having a story will make them more useful than just a list of businesses.

**Comment by morgajel** [comment]
you underestimate the scope of that work... I have 120+ different types of specialists, and a  city can have 40 prostitutes and 4 brothels... that's a lot ot variation.

**Comment by morgajel** [comment]
fixed with #111
