### ISSUE TITLE
lack of racial diversity in large cities

### ISSUE THREAD

**Issue by braddoro** [CityGenerator/CityGenerator#87]
I have seen two cities that are very large and both only have two races.  That seems inconsistent.  I would think there would be more.

http://devcitygenerator.morgajel.net/citygenerator?seed=792562
http://devcitygenerator.morgajel.net/citygenerator?seed=792531

**Comment by morgajel** [comment]
This appears to be caused by a bug in reusing the srand method; bad Jesse, no donut.

**Comment by morgajel** [comment]
So the root cause is due to reused seeds. If you use seed X and rand(100) returns a 91, every time you reset that seed the first rand(100) is going to be 91. Since most functions reset the seed to reduce drift when features are added, each city uses that "first dice roll" several times.  So if two cities have a first dice roll of 91, both cities have morals of 91; both have wind_roll of 91, both have a corruption roll of 91, both have a dominance_chance of 91 and both have a size_roll of 91

The solution is to add a subroutine-specific salt to each set_seed().
